// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package authorize

import (
	"github.com/houseme/yuncun-leping/app/front/api/authorize"
)

// ControllerV1 is for authorized controller implementation.
type ControllerV1 struct{}

// NewV1 creates and returns a new authorize controller object.
func NewV1() authorize.IAuthorizeV1 {
	return &ControllerV1{}
}
