// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/houseme/yuncun-leping/internal/database/dao/internal"
)

// internalHotCommentsDao is internal type for wrapping internal DAO implements.
type internalHotCommentsDao = *internal.HotCommentsDao

// hotCommentsDao is the data access object for table hot_comments.
// You can define custom methods on it to extend its functionality as you wish.
type hotCommentsDao struct {
	internalHotCommentsDao
}

var (
	// HotComments is globally public accessible object for table hot_comments operations.
	HotComments = hotCommentsDao{
		internal.NewHotCommentsDao(),
	}
)

// Fill with you ideas below.
