// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/houseme/yuncun-leping/internal/database/dao/internal"
)

// internalResponseLogDao is internal type for wrapping internal DAO implements.
type internalResponseLogDao = *internal.ResponseLogDao

// responseLogDao is the data access object for table response_log.
// You can define custom methods on it to extend its functionality as you wish.
type responseLogDao struct {
	internalResponseLogDao
}

var (
	// ResponseLog is globally public accessible object for table response_log operations.
	ResponseLog = responseLogDao{
		internal.NewResponseLogDao(),
	}
)

// Fill with you ideas below.
