// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/houseme/yuncun-leping/internal/database/dao/internal"
)

// internalSongsDao is internal type for wrapping internal DAO implements.
type internalSongsDao = *internal.SongsDao

// songsDao is the data access object for table songs.
// You can define custom methods on it to extend its functionality as you wish.
type songsDao struct {
	internalSongsDao
}

var (
	// Songs is globally public accessible object for table songs operations.
	Songs = songsDao{
		internal.NewSongsDao(),
	}
)

// Fill with you ideas below.
